services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: contactpassword2025
      POSTGRES_DB: contacts
    ports:
      - "5432:5432"
volumes:
  postgres_data: