"""Added Avatar

Revision ID: 4c121f35a17b
Revises: 16485e4e3b4c
Create Date: 2025-07-04 19:48:05.313507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c121f35a17b'
down_revision: Union[str, Sequence[str], None] = '16485e4e3b4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('contacts_email_key'), 'contacts', type_='unique')
    op.drop_constraint(op.f('contacts_name_key'), 'contacts', type_='unique')
    op.drop_constraint(op.f('contacts_phone_number_key'), 'contacts', type_='unique')
    op.add_column('users', sa.Column('avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    op.create_unique_constraint(op.f('contacts_phone_number_key'), 'contacts', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('contacts_name_key'), 'contacts', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('contacts_email_key'), 'contacts', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('contacts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
